import { ADD_BILLING_AND_SHIPPING_ADDRESS_KEY, ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_LOADING, ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_STATUS, STATUS, MESSAGE, ADD_BILLING_AND_SHIPPING_ADDRESS_FORM, ADD_BILLING_ADDRESS_FORM_ADDRESS, ADD_BILLING_ADDRESS_FORM_CITY, ADD_BILLING_ADDRESS_FORM_STATE, ADD_BILLING_ADDRESS_FORM_COUNTRY, ADD_BILLING_ADDRESS_FORM_NAME, ADD_BILLING_ADDRESS_FORM_PHONE, ADD_BILLING_ADDRESS_FORM_ZIP_CODE, ADD_SHIPPING_ADDRESS_FORM_ADDRESS, ADD_SHIPPING_ADDRESS_FORM_CITY, ADD_SHIPPING_ADDRESS_FORM_STATE, ADD_SHIPPING_ADDRESS_FORM_COUNTRY, ADD_SHIPPING_ADDRESS_FORM_NAME, ADD_SHIPPING_ADDRESS_FORM_PHONE, ADD_SHIPPING_ADDRESS_FORM_ZIP_CODE, IS_ADD_BILLING_ADDRESS_AS_SHIPPING_ADDRESS, ADD_BILLING_AND_SHIPPING_ADDRESS_RESET, ADD_BILLING_AND_SHIPPING_ADDRESS_UPDATE, LOG_OUT, ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_AUTOCOMPLETE_DATA, ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_TYPE, ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_AUTOCOMPLETE_LOADING, ADD_BILLING_AND_SHIPPING_ADDRESS_AUTOCOMPLETE_FORM_TEXT, ADD_BILLING_AND_SHIPPING_ADDRESS_AUTOCOMPLETE_FORM, SHIPPING, EMPTY, ADD_BILLING_AND_SHIPPING_ADDRESS_MODAL_IS_VISIBLE, ADD_BILLING_AND_SHIPPING_ADDRESS_MODAL_TYPE } from "../Types";

const INIT_STATE = {
    [ADD_BILLING_AND_SHIPPING_ADDRESS_KEY]: {
        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_LOADING]: false,
        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_AUTOCOMPLETE_LOADING]: false,
        [ADD_BILLING_AND_SHIPPING_ADDRESS_MODAL_IS_VISIBLE]: false,
        [ADD_BILLING_AND_SHIPPING_ADDRESS_MODAL_TYPE]: EMPTY,
        [IS_ADD_BILLING_ADDRESS_AS_SHIPPING_ADDRESS]: true,
        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_AUTOCOMPLETE_DATA]: undefined,
        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_TYPE]: undefined,
        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_STATUS]: {
            [STATUS]: undefined,
            [MESSAGE]: undefined
        },
        [ADD_BILLING_AND_SHIPPING_ADDRESS_FORM]: {
            [ADD_BILLING_ADDRESS_FORM_ADDRESS]: "",
            [ADD_BILLING_ADDRESS_FORM_CITY]: "",
            [ADD_BILLING_ADDRESS_FORM_STATE]: "",
            [ADD_BILLING_ADDRESS_FORM_COUNTRY]: "",
            [ADD_BILLING_ADDRESS_FORM_NAME]: "",
            [ADD_BILLING_ADDRESS_FORM_PHONE]: "",
            [ADD_BILLING_ADDRESS_FORM_ZIP_CODE]: "",

            [ADD_SHIPPING_ADDRESS_FORM_ADDRESS]: "",
            [ADD_SHIPPING_ADDRESS_FORM_CITY]: "",
            [ADD_SHIPPING_ADDRESS_FORM_STATE]: "",
            [ADD_SHIPPING_ADDRESS_FORM_COUNTRY]: "",
            [ADD_SHIPPING_ADDRESS_FORM_NAME]: "",
            [ADD_SHIPPING_ADDRESS_FORM_PHONE]: "",
            [ADD_SHIPPING_ADDRESS_FORM_ZIP_CODE]: ""
        },
        [ADD_BILLING_AND_SHIPPING_ADDRESS_AUTOCOMPLETE_FORM]: {
            [ADD_BILLING_AND_SHIPPING_ADDRESS_AUTOCOMPLETE_FORM_TEXT]: ""
        }
    }
}

export default (state = INIT_STATE, action) => {
    switch (action.type) {
        case ADD_BILLING_AND_SHIPPING_ADDRESS_UPDATE:
            return { ...state, [ADD_BILLING_AND_SHIPPING_ADDRESS_KEY]: action.payload };
        case ADD_BILLING_AND_SHIPPING_ADDRESS_RESET:
        case LOG_OUT:
            return {
                ...state,
                ...{
                    [ADD_BILLING_AND_SHIPPING_ADDRESS_KEY]: {
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_LOADING]: false,
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_AUTOCOMPLETE_LOADING]: false,
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_MODAL_IS_VISIBLE]: false,
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_MODAL_TYPE]: EMPTY,
                        [IS_ADD_BILLING_ADDRESS_AS_SHIPPING_ADDRESS]: true,
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_AUTOCOMPLETE_DATA]: undefined,
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_TYPE]: undefined,
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_REQUEST_STATUS]: {
                            [STATUS]: undefined,
                            [MESSAGE]: undefined
                        },
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_FORM]: {
                            [ADD_BILLING_ADDRESS_FORM_ADDRESS]: "",
                            [ADD_BILLING_ADDRESS_FORM_CITY]: "",
                            [ADD_BILLING_ADDRESS_FORM_STATE]: "",
                            [ADD_BILLING_ADDRESS_FORM_COUNTRY]: "",
                            [ADD_BILLING_ADDRESS_FORM_NAME]: "",
                            [ADD_BILLING_ADDRESS_FORM_PHONE]: "",
                            [ADD_BILLING_ADDRESS_FORM_ZIP_CODE]: "",
                
                            [ADD_SHIPPING_ADDRESS_FORM_ADDRESS]: "",
                            [ADD_SHIPPING_ADDRESS_FORM_CITY]: "",
                            [ADD_SHIPPING_ADDRESS_FORM_STATE]: "",
                            [ADD_SHIPPING_ADDRESS_FORM_COUNTRY]: "",
                            [ADD_SHIPPING_ADDRESS_FORM_NAME]: "",
                            [ADD_SHIPPING_ADDRESS_FORM_PHONE]: "",
                            [ADD_SHIPPING_ADDRESS_FORM_ZIP_CODE]: ""
                        },
                        [ADD_BILLING_AND_SHIPPING_ADDRESS_AUTOCOMPLETE_FORM]: {
                            [ADD_BILLING_AND_SHIPPING_ADDRESS_AUTOCOMPLETE_FORM_TEXT]: ""
                        }
                    }
                }
            }
        default:
            return state;
    }
};