import { HOME_KEY, HOME_REQEUST_CATEGORY_LOADING, HOME_REQEUST_CATEGORY_DATA, HOME_REQUEST_STATUS, STATUS, MESSAGE, HOME_REQEUST_SUB_CATEGORY_DATA_LOADING, HOME_REQEUST_SUB_CATEGORY_DATA, HOME_UPDATE, HOME_RESET, HOME_REQEUST_SEARCH_DATA, HOME_REQEUST_SEARCH_DATA_LOADING, HOME_REQEUST_IS_SHOW_SEARCH_LIST, HOME_REQUEST_CATEGORY_PAGE, HOME_REQUEST_CATEGORY_PAGE_SIZE, HOME_REQUEST_SUB_CATEGORY_PAGE, HOME_REQUEST_SUB_CATEGORY_PAGE_SIZE, HOME_REQUEST_SEARCH_PAGE, HOME_REQUEST_SEARCH_PAGE_SIZE, HOME_REQEUST_SEARCH_TEXT, HOME_REQEUST_SELECTED_CATEGORY_ID, LOG_OUT, HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA_LOADING, HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA, HOME_REQEUST_VIEW_ALL_SELECTED_SUB_CATEGORY_ID, HOME_REQEUST_VIEW_ALL_SELECTED_CATEGORY_ID, HOME_REQUEST_SUB_CATEGORY_PRODUCT_LIST_PAGE, HOME_REQUEST_SUB_CATEGORY_PRODUCT_LIST_PAGE_SIZE, HOME_REQEUST_CATEGORY_REFRESH_LOADING, HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA_REFRESH_LOADING, HOME_REQUEST_SUB_CATEGORY_SELECTED_SORT, HOME_REQUEST_SUB_CATEGORY_IS_VISIBLE_SORT_ALERT } from "../Types";

const INIT_STATE = {
    [HOME_KEY]: {
        [HOME_REQEUST_CATEGORY_LOADING]: false,
        [HOME_REQEUST_CATEGORY_REFRESH_LOADING]: false,
        [HOME_REQEUST_CATEGORY_DATA]: [],
        [HOME_REQUEST_CATEGORY_PAGE]: 1,
        [HOME_REQUEST_CATEGORY_PAGE_SIZE]: 100,

        [HOME_REQEUST_SUB_CATEGORY_DATA_LOADING]: false,
        [HOME_REQEUST_SUB_CATEGORY_DATA]: [],
        [HOME_REQUEST_SUB_CATEGORY_PAGE]: 1,
        [HOME_REQUEST_SUB_CATEGORY_PAGE_SIZE]: 100,

        [HOME_REQEUST_SEARCH_DATA_LOADING]: false,
        [HOME_REQEUST_SEARCH_DATA]: [],
        [HOME_REQEUST_SEARCH_TEXT]: "",
        [HOME_REQEUST_IS_SHOW_SEARCH_LIST]: false,
        [HOME_REQUEST_SEARCH_PAGE]: 1,
        [HOME_REQUEST_SEARCH_PAGE_SIZE]: 100,

        [HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA_LOADING]: false,
        [HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA_REFRESH_LOADING]: false,
        [HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA]: [],
        [HOME_REQEUST_VIEW_ALL_SELECTED_SUB_CATEGORY_ID]: "",
        [HOME_REQEUST_VIEW_ALL_SELECTED_CATEGORY_ID]: "",
        [HOME_REQUEST_SUB_CATEGORY_PRODUCT_LIST_PAGE]: 1,
        [HOME_REQUEST_SUB_CATEGORY_PRODUCT_LIST_PAGE_SIZE]: 100,

        [HOME_REQUEST_STATUS]: {
            [STATUS]: undefined,
            [MESSAGE]: undefined
        }
    }
}

export default (state = INIT_STATE, action) => {
    switch (action.type) {
        case HOME_UPDATE:
            return { ...state, [HOME_KEY]: action.payload };
        case HOME_RESET:
        case LOG_OUT:
            return {
                ...state,
                ...{
                    [HOME_KEY]: {
                        [HOME_REQEUST_CATEGORY_LOADING]: false,
                        [HOME_REQEUST_CATEGORY_DATA]: [],
                        [HOME_REQUEST_CATEGORY_PAGE]: 1,
                        [HOME_REQUEST_CATEGORY_PAGE_SIZE]: 100,

                        [HOME_REQEUST_SUB_CATEGORY_DATA_LOADING]: false,
                        [HOME_REQEUST_SUB_CATEGORY_DATA]: [],
                        [HOME_REQEUST_SELECTED_CATEGORY_ID]: "",
                        [HOME_REQUEST_SUB_CATEGORY_PAGE]: 1,
                        [HOME_REQUEST_SUB_CATEGORY_PAGE_SIZE]: 100,

                        [HOME_REQEUST_SEARCH_DATA_LOADING]: false,
                        [HOME_REQEUST_SEARCH_DATA]: [],
                        [HOME_REQEUST_SEARCH_TEXT]: "",
                        [HOME_REQEUST_IS_SHOW_SEARCH_LIST]: false,
                        [HOME_REQUEST_SEARCH_PAGE]: 1,
                        [HOME_REQUEST_SEARCH_PAGE_SIZE]: 100,

                        [HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA_LOADING]: false,
                        [HOME_REQEUST_SUB_CATEGORY_PRODUCT_LIST_DATA]: [],
                        [HOME_REQEUST_VIEW_ALL_SELECTED_SUB_CATEGORY_ID]: "",
                        [HOME_REQEUST_VIEW_ALL_SELECTED_CATEGORY_ID]: "",
                        [HOME_REQUEST_SUB_CATEGORY_PRODUCT_LIST_PAGE]: 1,
                        [HOME_REQUEST_SUB_CATEGORY_PRODUCT_LIST_PAGE_SIZE]: 100,

                        [HOME_REQUEST_SUB_CATEGORY_SELECTED_SORT]: "",
                        [HOME_REQUEST_SUB_CATEGORY_IS_VISIBLE_SORT_ALERT]: false,

                        [HOME_REQUEST_STATUS]: {
                            [STATUS]: undefined,
                            [MESSAGE]: undefined
                        }
                    }
                }
            }
        default:
            return state;
    }
};